### ISSUE TITLE
Update Java plugins

### ISSUE THREAD

**Issue by ammenzl7** [The-Charge/SteamBot2017#60]
Latest version is 2017.3.1

- [x] Andrew M.
- [x] Jessica K.
- [x] Shiva S.
- [x] Derek Y.
- [x] Cody K.
- [x] David W.
- [x] Kaedon C.
- [x] Colin W.
- [ ] Mr. Currie
- [ ] Mr. Wardin
- [ ] Mr. Rehberg
- [ ] Mr. Woods
- [x] Programmer 1
- [x] Programmer 3

**Comment by ghost** [comment]
WHAT DO I DO?????

**Comment by rwoodsmidl** [comment]
Kaedon,

Thanks for asking.  I've pushed up a version of the code that I've tried 
to make an improvement to but which isn't yet working. It involves GRIP 
module "Get Mat Info" or something like that. The intent is to utilize 
this module (which should run quite fast) to slowly modify camera 
settings while running video.  Right now the GRIP code (automatically 
generated upon request) apparently tries to determine the variable types 
of the parameters using Ref<T> which I'm not familiar with.  Note that 
we can't utilize the GRIP generated output code verbatim because we are 
dynamically making adjustments (predominantly during calibration) to HSL 
parameters.

Once we can retrieve the maximum value (think "the pixel with the 
brightest GREEN value sits at 255, or perhaps 100"), we will use that 
only when we are getting a decent image to adjust either the brightness, 
gain, or maybe even exposure or contrast to optimize the signal-to-noise 
ratio of the image.  I would think that we would try to maintain the 
strongest pixel value between 220 and 250 and my best guess is that 
we'll adjust brightness to do so.

Again, thanks,

Randy

P.S.  I'm hoping to work on the code some today but I can't be at robotics.
