### ISSUE TITLE
Investigate speed control for drive system to allow better control at low power settings

### ISSUE THREAD

**Issue by abcurrie** [The-Charge/SteamBot2017#72]

**Comment by Shalmezad** [comment]
May want to consider taking a look at SirLancebot since we have done this last year, specifically:
<hr/>

[SirLancebot Drivebase](https://github.com/The-Charge/SirLancebot2016/blob/master/src/org/usfirst/frc2619/SirLancebot2016/commands/DriveBase.java#L57
)
All our drive commands (tank, arcade, halo, clayton, etc) extended DriveBase. The commands implemented getLeft() and getRight(), DriveBase would use the current control method and feed those values to the drivetrain.

In particular, pay attention to how it says setRight**Percent**VBus(rightspeed); and setRightSpeed**Percentage**(rightspeed);

It does use a sendable chooser. If you want to implement this, it's in the [OI](https://github.com/The-Charge/SirLancebot2016/blob/master/src/org/usfirst/frc2619/SirLancebot2016/OI.java#L95)
<hr/>

[InitSpeedPercentageMode()](https://github.com/The-Charge/SirLancebot2016/blob/master/src/org/usfirst/frc2619/SirLancebot2016/subsystems/DriveTrain.java#L130) In the drivetrain, switches it to use speed "percentage" mode (it's the CANTalon speed control mode, the percentage comes into play in the next part)


[setLeftSpeedPercentage()](https://github.com/The-Charge/SirLancebot2016/blob/master/src/org/usfirst/frc2619/SirLancebot2016/subsystems/DriveTrain.java#L122) Has the magic for going from percentage to speed control.
